from __future__ import annotations

DEFAULT_PERPETUAL_PRODUCTS = [
    "BTC-PERP",
    "ETH-PERP",
    "SOL-PERP",
    "XRP-PERP",
]

DEFAULT_SIGNAL_GRANULARITY = "ONE_MINUTE"
DEFAULT_CONTEXT_GRANULARITY = "FIVE_MINUTE"
